name: Trigger auto deployment for webapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webapp-AutoDeployTrigger-9a77e9a5-2d84-4c95-b080-5de2976c2f4e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: webapplication361.azurecr.io
          registryUsername: ${{ secrets.WEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPP_REGISTRY_PASSWORD }}
          containerAppName: webapp
          resourceGroup: WebApplication361
          imageToBuild: webapplication361.azurecr.io/webapp:${{ github.sha }}
          


